<template>
  <v-container class="grey lighten-5">
    <v-row
      class="mb-6"
      no-gutters
    >
      <v-col md="2">
        <v-card
          class="pa-2"
          outlined
          tile
        >
          Hi
        </v-card>
      </v-col>
      <v-col
        md="3"
        offset-md="3"
      >
        <v-card
          class="pa-2"
          outlined
          tile
        >
          There
        </v-card>
      </v-col>
    </v-row>
    <v-row
      class="mb-6"
      no-gutters
    >
      <v-col
        md="1"
        offset-md="4"
      >
        <v-card
          class="pa-2"
          outlined
          tile
        >
          This
        </v-card>
      </v-col>
      <v-col
        md="4"
        offset-md="3"
      >
        <v-card
          class="pa-2"
          outlined
          tile
        >
          Is
        </v-card>
      </v-col>
    </v-row>
    <v-row no-gutters>
      <v-col
        md="3"
        offset-md="2"
      >
        <v-card
          class="pa-2"
          outlined
          tile
        >
          Sparta
        </v-card>
      </v-col>
    </v-row>
  </v-container>
</template>